### ISSUE TITLE
How do you turn a folder of markdown files into a Tiddlywiki

### ISSUE THREAD

**Issue by anthrolisp** [khinsen/science-in-the-digital-era#1]
I'm really intrigued by your setup. How do you turn a folder of markdown files into a Tiddlywiki? Thank you in advance!

**Comment by khinsen** [comment]
The code is right here in this repository: https://github.com/khinsen/science-in-the-digital-era/blob/main/build_tw.sh

There is a first preprocessing step done by a Python script, which mainly translates the internal link syntax that works in GitHub previews to the internal link syntax required by TW. Then I use the node-based version of TW to insert each Markdown file as a tiddler into a prepared TiddlyWiki template. With the [Markdown plugin](https://tiddlywiki.com/plugins/tiddlywiki/markdown/), I can keep the tiddlers in Markdown syntax.

**Comment by anthrolisp** [comment]
I downloaded the repository. 

With the node-base TW installed, when i run 'python3 pages2tiddlers.py', i get the following:

```
Traceback (most recent call last):
  File "/home/justin/Downloads/science-in-the-digital-era-main/pages2tiddlers.py", line 23, in <module>
    for tiddler_file in os.listdir(tiddler_directory):
FileNotFoundError: [Errno 2] No such file or directory: 'tiddlers'

```

When I re-run the command after I get create a tiddlers folder, I get the following:

```
Scientific model
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/justin/Downloads/science-in-the-digital-era-main/pages2tiddlers.py", line 44, in <module>
    tw_creation_timestamp = tw_timestamps[-1]
IndexError: list index out of range
```
My goal is simply a minimal repository/setup where one can add markdown files to a directory (ideally, a directory of directories of markdown files) with which I can create TW's on the fly.

This is something everyone in TW community says is possible, some do, but I am unable to find a working model anywhere to reproduce and study. I've played with TW a lot in the past, but with minimal experience find the documentation uneasy to navigate.

Any help or advice in this endeavour would be greatly appreciated. 

Thank you in advance!

**Comment by khinsen** [comment]
Yes, you have to create an empty `tiddlers` directory. Git doesn't handle empty directories, so it's not in the repository.

The 'index out of range' happens if you haven't committed your Markdown files. The script takes the creation/modification dates from the git commits. No commit, no timestamp, empty list, index out of range!

What you want to do and what everybody says is possible is handled by the command
```
tiddlywiki --load tw-template.html --load tiddlers --output ./ --render "$:/core/save/all" science-in-the-digital-era.html text/plain
```
It isn't obvious to figure out, but it does what you need. The Python script is only necessary because my Markdown files are written to be legible on GitHub, requiring different link syntax.

What the command above does is
1. Load the template file `tw-template.html`. It's a TW with all the plugins, including in particular the Markdown plugin.
2. Add the files in directory `tiddlers` one by one as (Markdown) tiddlers. The files must have the right format, with the header etc.
3. Store the complete TW in `science-in-the-digital-era.html`

Just change the three file/directory names, and it should work for you.

One more detail: the template TW must be the same TW version as the TW code installed via node.js.

**Comment by anthrolisp** [comment]
I really appreciate this!!
One more question: what is the right format to use for the metadata (title, etc) for markdown files. It does not appear to be the same as that of the tiddler. Does it need to be in yaml?
Thank you again!

**Comment by khinsen** [comment]
There are two options. One is a JSON file for the complete tiddler, with header and body. What I use is the two-file version: a plain markdown file, plus a separate header file with '.meta' appended to the file name, which contains 'key: value' lines.

Example from my tiddler collection:

File "Binary code.md":
```
This page is [empty](#Empty%20page)

<br>
[Permanent link to this version](https://github.com/khinsen/science-in-the-digital-era/blob/c3729ded2c12ca5c3292f6f79ba3ff4d73428ca9/pages/Binary%20code.md) ([archive copy](https://archive.softwareheritage.org/swh:1:cnt:8b137891791fe96927ad78e64b0aad7bded08bdc))
```

File "Binary code.md.meta":
```
title: Binary code
type: text/x-markdown
created: 20220924182346000
modified: 20220924182346000
```

Only title and type are obligatory if I remember correctly.
